// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;


[Table("Appointment")]
public partial class Appointment
{
    [Key]  
    public int Id { get; set; }

    public int DoctorId { get; set; }

    public int PatientId { get; set; }

    [Column(TypeName = "bit")]
    public bool Finished { get; set; } = false;

    [Column(TypeName = "datetime")]
    public DateTime? Date { get; set; }

    [ForeignKey("DoctorId")]
    [InverseProperty("Appointments")]
    public virtual Doctor? Doctor { get; set; } 

    [ForeignKey("PatientId")]
    [InverseProperty("Appointments")]
    public virtual Patient? Patient { get; set; } 
}