// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

[Table("Bill")]
public partial class Bill
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "decimal(7, 2)")]
    public decimal Amount { get; set; }

    public DateOnly Date { get; set; }

    public bool Paid { get; set; } = false; 

    public int PatientId { get; set; }

    [ForeignKey("PatientId")]
    [InverseProperty("Bills")]
    public virtual Patient? Patient { get; set; }
}