// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DAL.Data;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

[Table("Doctor")]
public partial class Doctor
{
    [Key]
    public int Id { get; set; }

    [StringLength(40)]
    [Unicode(false)]
    public string Name { get; set; } = null!;

    public int Age { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? Address { get; set; }

    [Column(TypeName = "decimal(8, 2)")]
    public decimal? Salary { get; set; }

    public DoctorsRank Rank { get; set; }

    public Shift Shift { get; set; }

    [StringLength(450)]
    [ForeignKey(nameof(AppUser))]
    public string AspNetUsersId { get; set; }

    public int DepartmentId { get; set; }

    public AppUser? AppUser { get; set; }

    [InverseProperty("Doctor")]
    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    [ForeignKey("DepartmentId")]
    [InverseProperty("Doctors")]
    public virtual Department? Department { get; set; }

    [InverseProperty("Head")]
    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();
}