// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

[Table("Drug")]
public partial class Drug
{
    [Key]
    public int DrugId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Dose { get; set; }

    public int MedicalRecordId { get; set; }

    [ForeignKey("MedicalRecordId")]
    [InverseProperty("Drugs")]
    public virtual MedicalRecord? MedicalRecord { get; set; } 
}