// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

[Table("MedicalRecord")]
public partial class MedicalRecord
{
    [Key]
    public int Id { get; set; }

    public int? PatientId { get; set; }

    [Unicode(false)]
    public string? Diagnose { get; set; }

    [InverseProperty("MedicalRecord")]
    public virtual ICollection<Drug> Drugs { get; set; } = new List<Drug>();

    [ForeignKey("PatientId")]
    [InverseProperty("MedicalRecords")]
    public virtual Patient? Patient { get; set; }
}