// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;


[Table("Nurse_Patient")]
public partial class NursePatient
{
    [Key]
    public int Id { get; set; }

    [Column("Nurse_Id")]
    public int NurseId { get; set; }

    [Column("Patient_Id")]
    public int PatientId { get; set; }

    [Column("Care_Date")]
    public DateOnly? CareDate { get; set; }

    [ForeignKey("NurseId")]
    [InverseProperty("NursePatients")]
    public virtual Nurse Nurse { get; set; } = null!;

    [ForeignKey("PatientId")]
    [InverseProperty("NursePatients")]
    public virtual Patient Patient { get; set; } = null!;
}